export const SET_LOCAL_DATA = 'SET_LOCAL_DATA'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_CLIENT_EVN = 'SET_CLIENT_EVN'
export const SET_GLOBAL_OVERLAY_DATA = 'SET_GLOBAL_OVERLAY_DATA'
